version: '3.8'
services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./data:/app/data
  worker:
    build: .
    container_name: celery_worker
    command: celery -A background.celery.celery_app worker --loglevel=info --concurrency=2
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./data:/app/data
  flower:
    build: .
    container_name: celery_flower
    command: celery -A background.celery.celery_app flower --port=5555
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    ports:
      - "5555:5555"
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379" 